/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./layout/components/AppMain.vue')['default']
    Avatar: typeof import('./components/Avatar/index.vue')['default']
    Breadcrumb: typeof import('./layout/components/Breadcrumb/index.vue')['default']
    EditMenu: typeof import('./views/system/menu/components/editMenu.vue')['default']
    EditRole: typeof import('./views/system/role/components/editRole.vue')['default']
    EditUser: typeof import('./views/system/user/components/editUser.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    Hamburger: typeof import('./components/Hamburger/index.vue')['default']
    Logo: typeof import('./layout/components/Sidebar/logo.vue')['default']
    Navbar: typeof import('./layout/components/Navbar.vue')['default']
    RightPanel: typeof import('./components/RightPanel/index.vue')['default']
    RoleMenu: typeof import('./views/system/role/components/roleMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./components/Screenfull/index.vue')['default']
    Settings: typeof import('./layout/components/Settings/index.vue')['default']
    Sidebar: typeof import('./layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./layout/components/Sidebar/SidebarItem.vue')['default']
    SidebarItemLink: typeof import('./layout/components/Sidebar/SidebarItemLink.vue')['default']
    SizeSelect: typeof import('./components/SizeSelect/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TagsView: typeof import('./layout/components/TagsView/index.vue')['default']
    ThemePicker: typeof import('./components/ThemePicker/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
